// AUTO-GENERATED by build-cheatsheets.js from https://github.com/cheat/cheatsheets
var CHEATSHEETS = {
  "tar": [
    {
      "desc": "To extract an uncompressed archive:",
      "code": "tar -xvf /path/to/foo.tar"
    },
    {
      "desc": "To extract a .tar in specified directory:",
      "code": "tar -xvf /path/to/foo.tar -C /path/to/destination/"
    },
    {
      "desc": "To create an uncompressed archive:",
      "code": "tar -cvf /path/to/foo.tar /path/to/foo/"
    },
    {
      "desc": "To extract a .tgz or .tar.gz archive:",
      "code": "tar -xzvf /path/to/foo.tgz\ntar -xzvf /path/to/foo.tar.gz"
    },
    {
      "desc": "To create a .tgz or .tar.gz archive:",
      "code": "tar -czvf /path/to/foo.tgz /path/to/foo/\ntar -czvf /path/to/foo.tar.gz /path/to/foo/"
    },
    {
      "desc": "To list the content of an .tgz or .tar.gz archive:",
      "code": "tar -tzvf /path/to/foo.tgz\ntar -tzvf /path/to/foo.tar.gz"
    },
    {
      "desc": "To extract a .tar.bz2 archive:",
      "code": "tar -xjvf /path/to/foo.tar.bz2"
    },
    {
      "desc": "To create a .tar.bz2 archive:",
      "code": "tar -cjvf /path/to/foo.tar.bz2 /path/to/foo/"
    },
    {
      "desc": "To list the content of an .tar.bz2 archive:",
      "code": "tar -tjvf /path/to/foo.tar.bz2"
    },
    {
      "desc": "To create a .tgz archive and exclude all jpg,gif,... from the tgz:",
      "code": "tar -czvf /path/to/foo.tgz --exclude=\\*.{jpg,gif,png,wmv,flv,tar.gz,zip} /path/to/foo/"
    },
    {
      "desc": "To use parallel (multi-threaded) implementation of compression algorithms:",
      "code": "tar -z ... -> tar -Ipigz ...\ntar -j ... -> tar -Ipbzip2 ...\ntar -J ... -> tar -Ipixz ..."
    },
    {
      "desc": "To append a new file to an old tar archive:",
      "code": "tar -rf <archive.tar> <new-file-to-append>"
    }
  ],
  "git": [
    {
      "desc": "To set your identity:",
      "code": "git config --global user.name <name>\ngit config --global user.email <email>"
    },
    {
      "desc": "To set your editor:",
      "code": "git config --global core.editor <editor>"
    },
    {
      "desc": "To enable color:",
      "code": "git config --global color.ui true"
    },
    {
      "desc": "To stage all changes for commit:",
      "code": "git add --all"
    },
    {
      "desc": "from the stash anytime",
      "code": "git stash"
    },
    {
      "desc": "To stash changes with a message:",
      "code": "git stash push -m <message>"
    },
    {
      "desc": "To list all the stashed changes:",
      "code": "git stash list"
    },
    {
      "desc": "To apply the most recent change and remove the stash from the stash list:",
      "code": "git stash pop"
    },
    {
      "desc": "from the stash list",
      "code": "git stash apply stash@{6}"
    },
    {
      "desc": "To commit staged changes:",
      "code": "git commit -m <message>"
    },
    {
      "desc": "To edit previous commit message:",
      "code": "git commit --amend"
    },
    {
      "desc": "Git commit in the past",
      "code": "git commit --date=\"`date --date='2 day ago'`\"\ngit commit --date=\"Jun 13 18:30:25 IST 2015\""
    },
    {
      "desc": "To change the date of an existing commit:",
      "code": "git filter-branch --env-filter \\\n'if [ $GIT_COMMIT = 119f9ecf58069b265ab22f1f97d2b648faf932e0 ]\nthen\nexport GIT_AUTHOR_DATE=\"Fri Jan 2 21:38:53 2009 -0800\"\nexport GIT_COMMITTER_DATE=\"Sat May 19 01:01:01 2007 -0700\"\nfi'"
    },
    {
      "desc": "To remove staged and working directory changes:",
      "code": "git reset --hard"
    },
    {
      "desc": "To go 2 commits back:",
      "code": "git reset --hard HEAD~2"
    },
    {
      "desc": "Checkout the fb branch, and rebase from <remote>",
      "code": "git reset --hard <remote>/<branch>"
    },
    {
      "desc": "fatal: ambiguous argument 'HEAD~1': unknown revision or path not in the working tree.",
      "code": "git update-ref -d HEAD"
    },
    {
      "desc": "To remove untracked files:",
      "code": "git clean -f -d"
    },
    {
      "desc": "To remove untracked and ignored files:",
      "code": "git clean -f -d -x"
    },
    {
      "desc": "To push to the tracked master branch:",
      "code": "git push origin master"
    },
    {
      "desc": "To push to a specified repository:",
      "code": "git push git@github.com:<username>/<repo>.git"
    },
    {
      "desc": "Tags: Tag a commit",
      "code": "git tag -a <tag> <commit> -m \"<commit message>\""
    },
    {
      "desc": "Tags: To push a tag to remote:",
      "code": "git push origin <tagname>"
    },
    {
      "desc": "Tags: To delete a tag <tagname> on remote",
      "code": "git push --delete origin <tagname>"
    },
    {
      "desc": "Tags: To delete a tag locally",
      "code": "git tag -d <tagname>"
    },
    {
      "desc": "To force a push:",
      "code": "git push -f"
    },
    {
      "desc": "Branches: To delete the branch <branch>:",
      "code": "git branch -D <branch>"
    },
    {
      "desc": "Branches: To delete a local <branch>:",
      "code": "git branch -d <branch>"
    },
    {
      "desc": "Branches: To delete a remote branch <branch>:",
      "code": "git push --delete origin <branch>"
    },
    {
      "desc": "Branches: To delete all branches on remote that are already merged:",
      "code": "git branch --merged | egrep -v \"(^*|main|dev)\" | xargs git branch -d"
    },
    {
      "desc": "Branches: To make an exisiting branch track a remote branch:",
      "code": "git branch -u upstream/foo"
    },
    {
      "desc": "To see who commited which line in a file:",
      "code": "git blame <file>"
    },
    {
      "desc": "To sync a fork with the master repo:",
      "code": "git remote add upstream git@github.com:<username>/<repo>.git # Set a new repo\ngit remote -v                                                # Confirm new remote repo\ngit fetch upstream                                           # Get branches\ngit branch -va                                               # List local - remote branches\ngit checkout master                                          # Checkout local master branch\ngit checkout -b new_branch                                   # Create and checkout a new branch\ngit merge upstream/master                                    # Merge remote into local repo\ngit show 83fb499                                             # Show what a commit did.\ngit show 83fb499:path/fo/file.ext                            # Shows the file as it appeared at 83fb499.\ngit diff branch_1 branch_2                                   # Check difference between branches\ngit log                                                      # Show all the commits\ngit status                                                   # Show the changes from last commit"
    },
    {
      "desc": "To view the commit history of a set of files:",
      "code": "git log --pretty=email --patch-with-stat --reverse --full-index -- Admin\\*.py > Sripts.patch"
    },
    {
      "desc": "To import commits from another repo:",
      "code": "git --git-dir=../some_other_repo/.git format-patch -k -1 --stdout <commit SHA> | git am -3 -k"
    },
    {
      "desc": "To view commits that will be pushed:",
      "code": "git log @{u}.."
    },
    {
      "desc": "To view changes that are new on a feature branch:",
      "code": "git log -p feature --not master\ngit diff master...feature"
    },
    {
      "desc": "To perform an interactive rebase for the prior 7 commits:",
      "code": "git rebase -i @~7"
    },
    {
      "desc": "This can be used to diff files that are not in a git repo!",
      "code": "git diff --no-index path/to/file/A path/to/file/B"
    },
    {
      "desc": "To pull changes while overwriting any local commits:",
      "code": "git fetch --all\ngit reset --hard origin/master"
    },
    {
      "desc": "the top of the incoming commits:",
      "code": "git pull <remote> <branch> --rebase"
    },
    {
      "desc": "To update all submodules:",
      "code": "git submodule update --init --recursive"
    },
    {
      "desc": "(helps save data when cloning large repos)",
      "code": "git clone --depth 1 <remote-url>"
    },
    {
      "desc": "To unshallow a clone:",
      "code": "git pull --unshallow"
    },
    {
      "desc": "To create a bare branch (one that has no commits on it):",
      "code": "git checkout --orphan branch_name"
    },
    {
      "desc": "To checkout a new branch from a different starting point:",
      "code": "git checkout -b master upstream/master"
    },
    {
      "desc": "you have a lot of useless branches, delete them on Github and then run this:",
      "code": "git remote prune origin"
    },
    {
      "desc": "To prune all remotes at once:",
      "code": "git remote prune $(git remote | tr '\\n' ' ')"
    },
    {
      "desc": "So, this will show the first commit that has \"cool\" in their message body",
      "code": "git show :/cool"
    },
    {
      "desc": "To undo parts of last commit in a specific file:",
      "code": "git checkout -p HEAD^ -- /path/to/file"
    },
    {
      "desc": "To revert a commit and keep the history of the reverted change as a separate revert commit:",
      "code": "git revert <commit SHA>"
    },
    {
      "desc": "merge as this just applies a single commit from a branch to current branch:",
      "code": "git cherry-pick <commit SHA1>"
    },
    {
      "desc": "Change author of a commit:",
      "code": "git commit --amend --author=\"Author Name <email@address.com>\""
    },
    {
      "desc": "The GPG key used for signing your commits",
      "code": "git config --global user.signingkey 0A46826A"
    },
    {
      "desc": "Sign new tags:",
      "code": "git tag -s v1.5 -m 'my signed 1.5 tag'"
    },
    {
      "desc": "Sign a commit:",
      "code": "git commit -a -S -m 'Signed commit'"
    },
    {
      "desc": "check any signatures it finds and list them in its output:",
      "code": "git log --pretty=\"format:%h %G? %aN %s\""
    },
    {
      "desc": "Defined the key to use for signing commits:",
      "code": "git config user.signingkey [KEYID]"
    },
    {
      "desc": "Set signing of commits globally:",
      "code": "git config --global commit.gpgsign true"
    },
    {
      "desc": "To list unstracked files:",
      "code": "git ls-files --others --exclude-standard"
    }
  ],
  "docker": [
    {
      "desc": "To start the docker daemon:",
      "code": "docker -d"
    },
    {
      "desc": "To build a docker image:",
      "code": "docker build -t <image-tag-name> <path-of-Dockerfile>"
    },
    {
      "desc": "To start a container with an interactive shell:",
      "code": "docker run -ti <image-name> /bin/bash"
    },
    {
      "desc": "To run a docker container in the background:",
      "code": "docker run -d <image-name>"
    },
    {
      "desc": "To \"shell\" into a running container (docker-1.3+):",
      "code": "docker exec -ti <container-name> bash"
    },
    {
      "desc": "To inspect a running container:",
      "code": "docker inspect <container-name> (or <container-id>)"
    },
    {
      "desc": "To get the process ID for a container:",
      "code": "docker inspect --format {{.State.Pid}} <container-name-or-id>"
    },
    {
      "desc": "To list (and pretty-print) the current mounted volumes for a container:",
      "code": "docker inspect --format='{{json .Volumes}}' <container-id> | python -mjson.tool"
    },
    {
      "desc": "To copy files/folders between a container and your host:",
      "code": "docker cp foo.txt mycontainer:/foo.txt"
    },
    {
      "desc": "To list currently running containers:",
      "code": "docker ps"
    },
    {
      "desc": "To list all containers:",
      "code": "docker ps -a"
    },
    {
      "desc": "To remove all stopped containers:",
      "code": "docker container prune"
    },
    {
      "desc": "To remove all stopped containers:",
      "code": "docker rm $(docker ps -qa)"
    },
    {
      "desc": "To list all images:",
      "code": "docker images"
    },
    {
      "desc": "To only see all images id:",
      "code": "docker image ls -q"
    },
    {
      "desc": "To remove all untagged images:",
      "code": "docker rmi $(docker images | grep \"^<none>\" | awk '{print $3}')"
    },
    {
      "desc": "To remove all volumes not used by at least one container:",
      "code": "docker volume prune"
    },
    {
      "desc": "To save image as tar archive:",
      "code": "docker save -o <archive-name>.tar <image-name>"
    },
    {
      "desc": "To restore image from a saved tar archive:",
      "code": "docker load -i <archive-name>.tar"
    },
    {
      "desc": "To remove an image:",
      "code": "docker image rm <image-name-or-id>"
    },
    {
      "desc": "To tag an image:",
      "code": "docker image tag <image-name>:<tag-name> <image-name>:<new-tag-name>"
    },
    {
      "desc": "To login into hub.docker.com:",
      "code": "docker login"
    },
    {
      "desc": "To push a docker image into dockerhub repository:",
      "code": "docker push <image-name>:<image-tag-name>"
    },
    {
      "desc": "List all networks daemon knows about:",
      "code": "docker network ls"
    },
    {
      "desc": "Create a specific network:",
      "code": "docker network create \"<network_name>\""
    },
    {
      "desc": "Connect a specific container to a network:",
      "code": "docker network connect \"<network_id|name>\" \"<container_id|name>\""
    },
    {
      "desc": "Disconnect a specific container from network:",
      "code": "docker network disconnect \"<network_id|name>\" \"<container_id|name>\""
    },
    {
      "desc": "To see the logs of a background or stopped container:",
      "code": "docker logs <container-id>"
    },
    {
      "desc": "To publish a port of container on localhost:",
      "code": "docker run -p <localhost-port>:<container-port> <image-name>"
    },
    {
      "desc": "To create a docker volume:",
      "code": "docker volume create <volume-name>"
    },
    {
      "desc": "To see information of a docker volume:",
      "code": "docker volume inspect <volume-name>"
    },
    {
      "desc": "To use a volume in the container:",
      "code": "docker run -v <volume-name>:<folder-path-in-container> <image>"
    },
    {
      "desc": "To link current folder between host and container for development:",
      "code": "docker run <image-name> -v $(pwd):<folder-path-in-container> <image>"
    },
    {
      "desc": "To copy a file from the running container to host mechine:",
      "code": "docker cp <container-id>:<path/to/file> <host/copy/path>"
    },
    {
      "desc": "To copy a file from host mechine to the running container:",
      "code": "docker cp <host/copy/path> <container-id>:<path/to/file>"
    }
  ],
  "docker-compose": [
    {
      "desc": "To start all containers defined in the docker-compose.yml file:",
      "code": "docker-compose up"
    },
    {
      "desc": "To start all containers defined in a given compose file:",
      "code": "docker-compose -f <path/to/compose_file.yml> up"
    },
    {
      "desc": "To start all containers in the background:",
      "code": "docker-compose up -d"
    },
    {
      "desc": "To rebuild the images before starting all containers:",
      "code": "docker-compose up --build"
    },
    {
      "desc": "To start only specific containers:",
      "code": "docker-compose up <container_name_1> <container_name_2>"
    },
    {
      "desc": "To list all running containers:",
      "code": "docker-compose ps"
    },
    {
      "desc": "To stop all running containers:",
      "code": "docker-compose stop"
    },
    {
      "desc": "To stop and remove all containers, networks, images, and volumes:",
      "code": "docker-compose down --rmi all --volumes"
    },
    {
      "desc": "To follow logs output from all containers:",
      "code": "docker-compose logs --follow"
    },
    {
      "desc": "To follow logs output from a specific container:",
      "code": "docker-compose logs --follow <container_name>"
    },
    {
      "desc": "To display the environment variables used by a running container:",
      "code": "docker-compose run <container_name> env"
    }
  ],
  "curl": [
    {
      "desc": "To download a file:",
      "code": "curl <url>"
    },
    {
      "desc": "To download and rename a file:",
      "code": "curl <url> -o <outfile>"
    },
    {
      "desc": "To download multiple files:",
      "code": "curl -O <url> -O <url>"
    },
    {
      "desc": "To download all sequentially numbered files (1-24):",
      "code": "curl http://example.com/pic[1-24].jpg"
    },
    {
      "desc": "To download a file and pass HTTP authentication:",
      "code": "curl -u <username>:<password> <url>"
    },
    {
      "desc": "To download a file with a proxy:",
      "code": "curl -x <proxy-host>:<port> <url>"
    },
    {
      "desc": "To download a file over FTP:",
      "code": "curl -u <username>:<password> -O ftp://example.com/pub/file.zip"
    },
    {
      "desc": "To get an FTP directory listing:",
      "code": "curl ftp://username:password@example.com"
    },
    {
      "desc": "To resume a previously failed download:",
      "code": "curl -C - -o <partial-file> <url>"
    },
    {
      "desc": "To fetch only the HTTP headers from a response:",
      "code": "curl -I <url>"
    },
    {
      "desc": "To fetch your external IP and network info as JSON:",
      "code": "curl http://ifconfig.me/all.json"
    },
    {
      "desc": "To limit the rate of a download:",
      "code": "curl --limit-rate 1000B -O <outfile>"
    },
    {
      "desc": "To get your global IP:",
      "code": "curl httpbin.org/ip"
    },
    {
      "desc": "To get only the HTTP status code:",
      "code": "curl -o /dev/null -w '%{http_code}\\n' -s -I URL"
    }
  ],
  "wget": [
    {
      "desc": "To download <url>:",
      "code": "wget <url>"
    },
    {
      "desc": "To download multiples files with multiple URLs:",
      "code": "wget <url>..."
    },
    {
      "desc": "To download <url> and change its name:",
      "code": "wget <url> -O <outfile>"
    },
    {
      "desc": "To download <url> into <dir>:",
      "code": "wget -P <dir> <url>"
    },
    {
      "desc": "To continue an aborted downloaded:",
      "code": "wget -c <url>"
    },
    {
      "desc": "To parse a file that contains a list of URLs to fetch each one:",
      "code": "wget -i url_list.txt"
    },
    {
      "desc": "To mirror a whole page locally:",
      "code": "wget -pk <url>"
    },
    {
      "desc": "To mirror a whole site locally:",
      "code": "wget -mk <url>"
    },
    {
      "desc": "To download files according to a pattern:",
      "code": "wget http://example.com/files-{1..15}.tar.bz2"
    },
    {
      "desc": "To download all the files in a directory with a specific extension if directory indexing is enabled:",
      "code": "wget -r -l1 -A.extension http://example.com/directory"
    },
    {
      "desc": "To download only response headers (-S --spider) and display them on stdout (-O -).:",
      "code": "wget -S --spider -O - <url>"
    },
    {
      "desc": "To change the User-Agent to 'User-Agent: toto':",
      "code": "wget -U 'toto' <url>"
    },
    {
      "desc": "To download a file with specific speed EX:500kb/sec:",
      "code": "wget --limit-rate=500k <url>"
    }
  ],
  "grep": [
    {
      "desc": "To search a file for a pattern:",
      "code": "grep <pattern> <file>"
    },
    {
      "desc": "To perform a case-insensitive search (with line numbers):",
      "code": "grep -in <pattern> <file>"
    },
    {
      "desc": "To recursively grep for string <pattern> in <dir>:",
      "code": "grep -R <pattern> <dir>"
    },
    {
      "desc": "Read search patterns from a file (one per line):",
      "code": "grep -f <pattern-file> <file>"
    },
    {
      "desc": "Find lines NOT containing pattern:",
      "code": "grep -v <pattern> <file>"
    },
    {
      "desc": "Set how many lines to show before (-B) and after (-A) pattern:",
      "code": "grep -B 3 -A 2 <pattern> <file>"
    },
    {
      "desc": "To grep with regular expressions:",
      "code": "grep \"^00\" <file>                                               # Match lines starting with 00\ngrep -E \"[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\" <file> # Find IP add"
    },
    {
      "desc": "To find all files that match <pattern> in <dir>",
      "code": "grep -rnw <dir> -e <pattern>"
    },
    {
      "desc": "(Add [] to the first letter. Ex: sshd -> [s]shd)",
      "code": "ps aux | grep '[h]ttpd'"
    },
    {
      "desc": "Colour in red {bash} and keep all other lines",
      "code": "ps aux | grep -E --color 'bash|$'"
    }
  ],
  "find": [
    {
      "desc": "To find files following symlinks (otherwise the symlinks are not followed):",
      "code": "find -L . -type f"
    },
    {
      "desc": "To find files by case-insensitive extension (ex: .jpg, .JPG, .jpG):",
      "code": "find . -iname \"*.jpg\""
    },
    {
      "desc": "To find directories:",
      "code": "find . -type d"
    },
    {
      "desc": "To find files:",
      "code": "find . -type f"
    },
    {
      "desc": "To find files by octal permission:",
      "code": "find . -type f -perm 777"
    },
    {
      "desc": "To find files with setuid bit set:",
      "code": "find . -xdev \\( -perm -4000 \\) -type f -print0 | xargs -0 ls -l"
    },
    {
      "desc": "To find files newer than 1 day old and copy elsewhere (remove -p flag in xargs to not be asked):",
      "code": "find . -type f -ctime -1 -print0 | xargs -0 -p cp -t <dir>"
    },
    {
      "desc": "or:",
      "code": "find . -type f -ctime -1 -print0 | xargs -0 -p -J % cp % <dir>"
    },
    {
      "desc": "To find files with extension '.txt' and remove them:",
      "code": "find ./path/ -name '*.txt' -delete"
    },
    {
      "desc": "To find files with tilde as postfix and remove them:",
      "code": "find ./path/ -name '*~' -delete"
    },
    {
      "desc": "To find files with extension '.txt' and dump their contents:",
      "code": "find ./path/ -name '*.txt' -exec cat '{}' \\;"
    },
    {
      "desc": "To find files with extension '.txt' and look for a string into them:",
      "code": "find ./path/ -name '*.txt' | xargs grep 'string'"
    },
    {
      "desc": "To find files with size bigger than 5 Mebibyte and sort them by size:",
      "code": "find . -size +5M -type f -print0 | xargs -0 ls -Ssh | sort -z"
    },
    {
      "desc": "To find files bigger than 2 Megabyte and list them:",
      "code": "find . -type f -size +200000000c -exec ls -lh {} \\; | awk '{ print $9 \": \" $5 }'"
    },
    {
      "desc": "To find files modified more than 7 days ago and list file information:",
      "code": "find . -type f -mtime +7d -ls"
    },
    {
      "desc": "To find symlinks owned by a user and list file information:",
      "code": "find . -type l -user <username-or-userid> -ls"
    },
    {
      "desc": "To search for and delete empty directories:",
      "code": "find . -type d -empty -exec rmdir {} \\;"
    },
    {
      "desc": "To search for directories named build at a max depth of 2 directories:",
      "code": "find . -maxdepth 2 -name build -type d"
    },
    {
      "desc": "To search all files who are not in .git directory:",
      "code": "find . ! -iwholename '*.git*' -type f"
    },
    {
      "desc": "To find all files that have the same node (hard link) as MY_FILE_HERE:",
      "code": "find . -type f -samefile MY_FILE_HERE 2>/dev/null"
    },
    {
      "desc": "To find all files in the current directory and modify their permissions:",
      "code": "find . -type f -exec chmod 644 {} \\;"
    },
    {
      "desc": "To find all files changed in last 2 days:",
      "code": "find . -type f -ctime -48h\nfind . -type f -ctime -2"
    },
    {
      "desc": "Or created in last 2 days:",
      "code": "find . -type f -Btime -2"
    },
    {
      "desc": "Or accessed in last 2 days:",
      "code": "find . -type f -atime -2"
    },
    {
      "desc": "name (dry-run):",
      "code": "find . -name '*,*' | while read f; do echo mv \"$f\" \"${f//,/}\"; done"
    },
    {
      "desc": "To find all broken links. Note -L returns a file unless it is a broken link:",
      "code": "find -L /usr/ports/packages -type l"
    },
    {
      "desc": "See: https://stackoverflow.com/questions/5119946/find-exec-with-multiple-commands",
      "code": "find . -type f -exec sh -c \"echo '{}'; cat '{}';\" \\;"
    },
    {
      "desc": "To find files that are newer than a file:",
      "code": "find <path> -newer <target-file>"
    }
  ],
  "sed": [
    {
      "desc": "To replace all occurrences of \"day\" with \"night\" and write to stdout:",
      "code": "sed 's/day/night/g' <file>"
    },
    {
      "desc": "To replace all occurrences of \"day\" with \"night\" within <file>:",
      "code": "sed -i 's/day/night/g' <file>"
    },
    {
      "desc": "To replace all occurrences of \"day\" with \"night\" on stdin:",
      "code": "echo 'It is daytime' | sed 's/day/night/g'"
    },
    {
      "desc": "To remove leading spaces:",
      "code": "sed -i -r 's/^\\s+//g' <file>"
    },
    {
      "desc": "To remove empty lines and print results to stdout:",
      "code": "sed '/^$/d' <file>"
    },
    {
      "desc": "To replace newlines in multiple lines:",
      "code": "sed ':a;N;$!ba;s/\\n//g' <file>"
    },
    {
      "desc": "To insert a line before a matching pattern:",
      "code": "sed '/Once upon a time/i\\Chapter 1'"
    },
    {
      "desc": "To add a line after a matching pattern:",
      "code": "sed '/happily ever after/a\\The end.'"
    }
  ],
  "awk": [
    {
      "desc": "To sum integers from a file or stdin, one integer per line:",
      "code": "printf '1\\n2\\n3\\n' | awk '{ sum += $1} END {print sum}'"
    },
    {
      "desc": "To use a specific character as separator to sum integers from a file or stdin:",
      "code": "printf '1:2:3' | awk -F \":\" '{print $1+$2+$3}'"
    },
    {
      "desc": "To print a multiplication table:",
      "code": "seq 9 | sed 'H;g' | awk -v RS='' '{for(i=1;i<=NF;i++)printf(\"%dx%d=%d%s\", i, NR, i*NR, i==NR?\"\\n\":\"\\t\")}'"
    },
    {
      "desc": "To specify an output separator character:",
      "code": "printf '1 2 3' | awk 'BEGIN {OFS=\":\"}; {print $1,$2,$3}'"
    },
    {
      "desc": "To execute commands only on rows that satisfy a certain condtion",
      "code": "printf \"george jetson\\nolive oyl\\nbeetle bailey\" | awk '$2==\"bailey\"{print $0}'"
    },
    {
      "desc": "To execute commands only on matching rows using regex",
      "code": "printf \"george jetson\\nolive oyl\\nbeetle bailey\" | awk '/ley$/{print $0}'"
    }
  ],
  "rsync": [
    {
      "desc": "(-a), zipping for faster transfer (-z), verbose (-v):",
      "code": "rsync -avz host:file1 :file1 /dest/\nrsync -avz /source host:/dest"
    },
    {
      "desc": "changed. (Useful for validating backups):",
      "code": "rsync -avc <src> <dest>"
    },
    {
      "desc": "This command will create /dest/foo if it does not already exist",
      "code": "rsync -auv /src/foo /dest"
    },
    {
      "desc": "This command will not create /foo_bak/foo folder",
      "code": "rsync -auv /src/foo/ /foo_bak"
    },
    {
      "desc": "destination folder in remoteuser's home directory:",
      "code": "rsync -avz -e \"ssh -p1234\" <source> <username>@<host>:<dest>"
    },
    {
      "desc": "in remote's authorized_keys, e.g. using ssh-copy-id)",
      "code": "rsync -avz -e \"ssh -i ~/.ssh/id_rsa\" <src> <dest>"
    },
    {
      "desc": "Log into remote as a user, but promote to root, to access privileged files:",
      "code": "rsync -avz --rsync-path=\"sudo rsync\" user@<src> <dest>"
    },
    {
      "desc": "Rsync only symlinks and preserve them as symlinks (dont follow them):",
      "code": "find /path/to/files -type l -print | \\\nrsync -av --files-from=- /path/to/files user@targethost:/dest_path"
    }
  ],
  "scp": [
    {
      "desc": "To copy a file from your local machine to a remote server:",
      "code": "scp <file> <user>@<host>:<dest>"
    },
    {
      "desc": "To copy a file from a remote server to your local machine:",
      "code": "scp <user>@<host>:<src> <dest>"
    },
    {
      "desc": "To scp a file over a SOCKS proxy on localhost and port 9999 (see ssh for tunnel setup):",
      "code": "scp -o \"ProxyCommand nc -x 127.0.0.1:9999 -X 4 %h %p\" <file> <user>@<host>:<dest>"
    },
    {
      "desc": "To scp between two remote servers from the third machine:",
      "code": "scp -3 <user>@<host1>:<src> <user>@<host2>:<dest>"
    }
  ],
  "ssh": [
    {
      "desc": "To ssh via pem file (which normally needs 0600 permissions):",
      "code": "ssh -i <pemfile> <user>@<host>"
    },
    {
      "desc": "To connect on a non-standard port:",
      "code": "ssh -p <port> <user>@<host>"
    },
    {
      "desc": "To connect and forward the authentication agent:",
      "code": "ssh -A <user>@<host>"
    },
    {
      "desc": "To execute a command on a remote server:",
      "code": "ssh -t <user>@<host> 'the-remote-command'"
    },
    {
      "desc": "Full list of available algorithms : man ssh_config",
      "code": "ssh -oKeXAlgorithms=+diffie-hellman-group-exchange-sha1 <user>@<server>"
    },
    {
      "desc": "To tunnel an x session over SSH:",
      "code": "ssh -X <user>@<host>"
    },
    {
      "desc": "host (remote.example.com:5000) through a proxy (personal.server.com):",
      "code": "ssh -f -L 8080:remote.example.com:5000 user@personal.server.com -N"
    },
    {
      "desc": "To launch a specific x application over SSH:",
      "code": "ssh -X -t <user>@<host> 'chromium-browser'"
    },
    {
      "desc": "To create a SOCKS proxy on localhost and <port>:",
      "code": "ssh -qND <port> <user>@<host>"
    },
    {
      "desc": "To tunnel an ssh session over the SOCKS proxy on localhost and port 9999:",
      "code": "ssh -o \"ProxyCommand nc -x 127.0.0.1:9999 -X 4 %h %p\" <user>@<host>"
    },
    {
      "desc": "-X use an xsession, -C compress data, \"-c blowfish\" use the encryption blowfish:",
      "code": "ssh <user>@<host> -C -c blowfish -X"
    },
    {
      "desc": "compression when there is no rsync command available:",
      "code": "ssh <user>@<host> \"cd /var/www/Shared/; tar zcf - asset1 asset2\" | tar zxf -"
    },
    {
      "desc": "Will allow you to mount a folder securely over a network.",
      "code": "sshfs <user>@<host>:/path/to/folder /path/to/mount/point"
    },
    {
      "desc": "Doc: http://www.gnu.org/software/emacs/manual/html_node/emacs/Remote-Files.html",
      "code": "emacs /ssh:<user>@<host>:<file>"
    }
  ],
  "ssh-keygen": [
    {
      "desc": "To generate an SSH key:",
      "code": "ssh-keygen -t rsa"
    },
    {
      "desc": "To generate a 4096-bit SSH key:",
      "code": "ssh-keygen -t rsa -b 4096"
    },
    {
      "desc": "To generate a FIDO/U2F token-backed key:",
      "code": "ssh-keygen -t ed25519-sk"
    },
    {
      "desc": "To generate a FIDO2 resident key:",
      "code": "ssh-keygen -t ed25519-sk -O resident"
    },
    {
      "desc": "To update a passphrase on a key:",
      "code": "ssh-keygen -p -P <old-passphrase> -N <new-passphrase> -f <keyfile>"
    },
    {
      "desc": "To remove a passphrase on a key:",
      "code": "ssh-keygen -p -P <old-passphrase> -N '' -f <keyfile>"
    },
    {
      "desc": "To generate a 4096 bit RSA key with a passphase and comment containing the user and hostname:",
      "code": "ssh-keygen -t rsa -b 4096 -C \"$USER@$HOSTNAME\" -P <passphrase>"
    },
    {
      "desc": "To print the fingerprint of a public key:",
      "code": "ssh-keygen -lf <keyfile>"
    },
    {
      "desc": "To print the Github-style (MD5) fingerprint of a public key:",
      "code": "ssh-keygen -E md5 -lf <keyfile>"
    },
    {
      "desc": "To download resident keys from a FIDO2 authenticator to the current directory:",
      "code": "ssh-keygen -K"
    },
    {
      "desc": "To view the public key associated with a private key:",
      "code": "ssh-keygen -y -f <private-key-file> > <public-key-file>\nssh-keygen -y -f ~/.ssh/private-key > ~/.ssh/public-key.pub"
    }
  ],
  "npm": [
    {
      "desc": "To install a package in the current directory:",
      "code": "npm install <package>"
    },
    {
      "desc": "To install a package, and save it in the `dependencies` section of `package.json`:",
      "code": "npm install --save <package>"
    },
    {
      "desc": "To install a package, and save it in the `devDependencies` section of `package.json`:",
      "code": "npm install --save-dev <package>"
    },
    {
      "desc": "To show outdated packages in the current directory:",
      "code": "npm outdated"
    },
    {
      "desc": "To update outdated packages:",
      "code": "npm update"
    },
    {
      "desc": "To update `npm` (will override the one shipped with Node.js):",
      "code": "npm install -g npm"
    },
    {
      "desc": "To uninstall a package:",
      "code": "npm uninstall <package>"
    },
    {
      "desc": "To set the `authToken` using env variable `NPM_TOKEN`:",
      "code": "npm config set //npm.intra/:_authToken=\\${NPM_TOKEN}"
    }
  ],
  "python": [
    {
      "desc": "Python v2.7",
      "code": "python -m SimpleHTTPServer"
    },
    {
      "desc": "Python 3",
      "code": "python -m http.server 8000"
    },
    {
      "desc": "SMTP-Server for debugging, messages will be discarded, and printed on stdout.",
      "code": "python -m smtpd -n -c DebuggingServer localhost:1025"
    },
    {
      "desc": "Pretty print a json",
      "code": "python -m json.tool foo.json"
    }
  ],
  "pip": [
    {
      "desc": "To search for a package:",
      "code": "pip search <package>"
    },
    {
      "desc": "To install packages:",
      "code": "pip install <package>..."
    },
    {
      "desc": "To install a package in user space:",
      "code": "pip install --user <package>"
    },
    {
      "desc": "To upgrade a package:",
      "code": "pip install --upgrade <package>"
    },
    {
      "desc": "To output and install packages in a requirement file:",
      "code": "pip freeze > requirements.txt\npip install -r requirements.txt"
    },
    {
      "desc": "To show details of a package:",
      "code": "pip show <package>"
    },
    {
      "desc": "To list outdated packages:",
      "code": "pip list --outdated"
    },
    {
      "desc": "To upgrade all outdated packages:",
      "code": "pip freeze --local | grep -v '^\\-e' | cut -d = -f 1 | xargs -n1 pip install -U"
    },
    {
      "desc": "To upgrade outdated packages on latest version of pip:",
      "code": "pip list --outdated --format=freeze | cut -d = -f 1 | xargs -n1 pip install -U"
    },
    {
      "desc": "To install specific version of a package:",
      "code": "pip install -I SomePackage1==1.1.0 'SomePackage2>=1.0.4'"
    }
  ],
  "go": [
    {
      "desc": "To run the package in the current directory",
      "code": "go run ."
    },
    {
      "desc": "To run the package in the ./cmd/foo directory",
      "code": "go run ./cmd/foo/"
    },
    {
      "desc": "To fetch dependencies",
      "code": "go get github.com/foo/bar@v1.2.3\ngo get github.com/foo/bar@8e1b8d3"
    },
    {
      "desc": "Upgrade the dependency.",
      "code": "go get -u github.com/foo/bar"
    },
    {
      "desc": "Building an Executable.",
      "code": "go build -o=/tmp/foo . # Compile the package in the current directory\ngo build -o=/tmp/foo ./cmd/foo # Compile the package in the ./cmd/foo directory"
    },
    {
      "desc": "Build cache",
      "code": "go env GOCACHE # Check where your build cache is\ngo build -a -o=/tmp/foo . # Force all packages to be rebuilt\ngo clean -cache # Remove everything from the build cache"
    },
    {
      "desc": "Cross-Compilation",
      "code": "GOOS=linux GOARCH=amd64 go build -o=/tmp/linux_amd64/foo .\nGOOS=windows GOARCH=amd64 go build -o=/tmp/windows_amd64/foo.exe ."
    },
    {
      "desc": "List of all supported OS/architectures",
      "code": "go tool dist list"
    },
    {
      "desc": "To show all the dependencies of the module",
      "code": "go list -m all"
    },
    {
      "desc": "To sho why is that a dependency?",
      "code": "go mod why -m golang.org/x/sys"
    },
    {
      "desc": "Clear module cache",
      "code": "go clean -modcache"
    },
    {
      "desc": "View simplified documentation for the strings package",
      "code": "go doc strings"
    },
    {
      "desc": "View full documentation for the strings package",
      "code": "go doc -all strings"
    },
    {
      "desc": "View documentation for the strings.Replace function",
      "code": "go doc strings.Replace"
    },
    {
      "desc": "View documentation for the database/sql.DB type",
      "code": "go doc sql.DB"
    },
    {
      "desc": "View documentation for the database/sql.DB.Query method",
      "code": "go doc sql.DB.Query"
    },
    {
      "desc": "View the source code for the strings.Replace function",
      "code": "go doc -src strings.Replace"
    },
    {
      "desc": "Run all tests in the current directory",
      "code": "go test ."
    },
    {
      "desc": "Run all tests in the current directory and sub-directories",
      "code": "go test ./..."
    },
    {
      "desc": "Run all tests in the ./foo/bar directory",
      "code": "go test ./foo/bar"
    },
    {
      "desc": "Testing with race detector",
      "code": "go test -race ./..."
    },
    {
      "desc": "Bypass the test cache when running tests",
      "code": "go test -count=1 ./..."
    },
    {
      "desc": "Delete all cached test results",
      "code": "go clean -testcache"
    },
    {
      "desc": "Run the test with the exact name TestFooBar",
      "code": "go test -v -run=^TestFooBar$ ."
    },
    {
      "desc": "Run tests whose names start with TestFoo",
      "code": "go test -v -run=^TestFoo ."
    },
    {
      "desc": "Run the Baz subtest of the TestFooBar test only",
      "code": "go test -v -run=^TestFooBar$/^Baz$ ."
    },
    {
      "desc": "Handy flag - skip long running tests",
      "code": "go test -short ./..."
    },
    {
      "desc": "Handy flag - don't run further tests after a failure.",
      "code": "go test -failfast ./..."
    },
    {
      "desc": "Test all module dependencies.",
      "code": "go test all"
    },
    {
      "desc": "Stress testing",
      "code": "go test -run=^TestFooBar$ -count=500 ."
    },
    {
      "desc": "Upgrading the code to a New Go Release",
      "code": "go fix ./..."
    },
    {
      "desc": "Create a new Github issue for Go's standard library",
      "code": "go bug"
    },
    {
      "desc": "Running and Comparing Benchmarks",
      "code": "go test -bench=. ./... # Run all benchmarks and tests\ngo test -run=^$ -bench=. ./... # Run all benchmarks (and no tests)\ngo test -run=^$ -bench=^BenchmarkFoo$ ./... # Run only the BenchmarkFoo benchmark (and no tests)\ngo test -bench=. -benchmem ./... # Forces the output of memory allocation statistics\ngo test -bench=. -benchtime=5s ./... # Run each benchmark test for at least 5 seconds\ngo test -bench=. -benchtime=500x ./... # Run each benchmark test for exactly 500 iterations\ngo test -bench=. -count=3 ./... # Repeat each benchmark test 3 times over\ngo test -bench=. -cpu=1,4,8 ./... # Run benchmarks with GOMAXPROCS set to 1, 4 and 8"
    },
    {
      "desc": "Comparing changes between benchmarks",
      "code": "go get golang.org/x/tools/cmd/benchcmp@latest # Install the compare tool.\ngo test -run=^$ -bench=. -benchmem ./... > /tmp/old.txt # Measure benchmark before changes\ngo test -run=^$ -bench=. -benchmem ./... > /tmp/new.txt # Measure benchmark after changes\nbenchcmp /tmp/old.txt /tmp/new.txt  # Compare changes."
    },
    {
      "desc": "Using Compiler and Linker Flags",
      "code": "go tool compile -help # complete list of available compiler flags\ngo build -gcflags=\"-m -m\" -o=/tmp/foo . # print optimization decisions\ngo build -gcflags=\"all=-m\" -o=/tmp/foo . # optimization decisions for dependencies too\ngo build -gcflags=\"all=-N -l\" -o=/tmp/foo . # disable optimizations and inlining\ngo tool link -help # list of available linker flags\ngo build -ldflags=\"-X main.version=1.2.3\" -o=/tmp/foo . # add a version number\ngo build -ldflags=\"-s -w\" -o=/tmp/foo . # strip debug information from the binary\nCGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags \"-static\"' . # make the binary as static as possible"
    },
    {
      "desc": "Trace generation",
      "code": "go test -run=^$ -bench=^BenchmarkFoo$ -trace=/tmp/trace.out .\ngo tool trace /tmp/trace.out # Works only on Chrome / Chromium at the moment"
    },
    {
      "desc": "Viewing Environment Information",
      "code": "go env # List all environment variables.\ngo env -w GOPATH=/foo/bar # Set GOPATH environment variable to /foo/bar"
    },
    {
      "desc": "Checking for Race Conditions",
      "code": "go build -race -o=/tmp/foo . # not for production"
    }
  ],
  "systemctl": [
    {
      "desc": "To see running processes:",
      "code": "systemctl"
    },
    {
      "desc": "To check the status of a service:",
      "code": "systemctl status foo.service"
    },
    {
      "desc": "To start/restart/stop a service:",
      "code": "systemctl start/restart/stop foo.service"
    },
    {
      "desc": "To reload a service's configuration:",
      "code": "systemctl reload foo.service"
    },
    {
      "desc": "To edit a service's configuration:",
      "code": "systemctl edit foo.service"
    },
    {
      "desc": "To reload systemd manager configuration:",
      "code": "systemctl daemon-reload"
    },
    {
      "desc": "To enable a service to startup on boot:",
      "code": "systemctl enable foo.service"
    },
    {
      "desc": "To disable a service to startup on boot:",
      "code": "systemctl disable foo.service"
    },
    {
      "desc": "To start/restart/stop per-user service:",
      "code": "systemctl --user start/restart/stop emacs.service"
    },
    {
      "desc": "To see all active units, add --all for everything:",
      "code": "systemctl list-units"
    },
    {
      "desc": "To see all service units:",
      "code": "systemctl list-units -at service"
    },
    {
      "desc": "To see filtered units (all running service):",
      "code": "systemctl list-units -t service --state running"
    },
    {
      "desc": "To see all service files, see which are enabled or disabled:",
      "code": "systemctl list-unit-files -at service"
    },
    {
      "desc": "To list all units with specific status, inactive, active, enabled, running, exited:",
      "code": "systemctl list-units --all --state=inactive"
    },
    {
      "desc": "To use systemctl to list all unit files:",
      "code": "systemctl list-unit-files"
    },
    {
      "desc": "To see log items from the most recent boot:",
      "code": "journalctl -b"
    },
    {
      "desc": "To to see only kernal messages, add -b for at the most recent boot:",
      "code": "journalctl -k"
    },
    {
      "desc": "To get the log entries for a service since boot:",
      "code": "journalctl -b -u foo.service"
    },
    {
      "desc": "add -all to expand dependencies recursively",
      "code": "systemctl list-dependencies foo.service"
    },
    {
      "desc": "To see low level details of a service settings on the system:",
      "code": "systemctl show foo.service"
    },
    {
      "desc": "To list currently loaded targets:",
      "code": "systemctl list-units --type=target"
    },
    {
      "desc": "To change current target:",
      "code": "systemctl isolate foo.target"
    },
    {
      "desc": "To change default target:",
      "code": "systemctl enable foo.target"
    }
  ],
  "journalctl": [
    {
      "desc": "To actively follow log (like tail -f):",
      "code": "journalctl -f"
    },
    {
      "desc": "To display all errors since last boot:",
      "code": "journalctl -b -p err"
    },
    {
      "desc": "To filter by time period:",
      "code": "journalctl --since=2012-10-15 --until=\"2011-10-16 23:59:59\""
    },
    {
      "desc": "To show list of systemd units logged in journal:",
      "code": "journalctl -F _SYSTEMD_UNIT"
    },
    {
      "desc": "To filter by specific unit:",
      "code": "journalctl -u dbus"
    },
    {
      "desc": "To filter by executable name:",
      "code": "journalctl /usr/bin/dbus-daemon"
    },
    {
      "desc": "To filter by PID:",
      "code": "journalctl _PID=123"
    },
    {
      "desc": "To filter by Command, e.g., sshd:",
      "code": "journalctl _COMM=sshd"
    },
    {
      "desc": "To filter by Command and time period:",
      "code": "journalctl _COMM=crond --since '10:00' --until '11:00'"
    },
    {
      "desc": "To list all available boots:",
      "code": "journalctl --list-boots"
    },
    {
      "desc": "To filter by specific User ID e.g., user id 1000:",
      "code": "journalctl _UID=1000"
    },
    {
      "desc": "To filter by specific SYSLOG_INDENTIFIER:",
      "code": "journalctl -t systemd-resolved"
    }
  ],
  "crontab": [
    {
      "desc": "set a shell",
      "code": "SHELL=/bin/bash"
    },
    {
      "desc": "set a PATH",
      "code": "PATH=/usr/bin:/usr/sbin:/usr/local/bin"
    },
    {
      "desc": "incorrect way of seeting PATH",
      "code": "PATH=$PATH:/do/not/do/this"
    },
    {
      "desc": "crontab format",
      "code": "* * * * *  command_to_execute\n- - - - -\n| | | | |\n| | | | +- day of week (0 - 7) (where sunday is 0 and 7)\n| | | +--- month (1 - 12)\n| | +----- day (1 - 31)\n| +------- hour (0 - 23)\n+--------- minute (0 - 59)"
    },
    {
      "desc": "every 15 min",
      "code": "*/15 * * * * /home/user/command.sh"
    },
    {
      "desc": "every midnight",
      "code": "0 0 * * * /home/user/command.sh"
    },
    {
      "desc": "every Saturday at 8:05 AM",
      "code": "5 8 * * 6 /home/user/command.sh"
    },
    {
      "desc": "compute your crontab periodicity format online",
      "code": "https://crontab.guru/"
    },
    {
      "desc": "be careful with % sign (percent), it has special meaning, see https://crontab.guru/ for explanation",
      "code": "% signs must be escaped such as \\%"
    },
    {
      "desc": "view log",
      "code": "journalctl | grep CRON"
    }
  ],
  "vim": [
    {
      "desc": "File management",
      "code": ":e              reload file\n:q              quit\n:q!             quit without saving changes\n:w              write file\n:w {file}       write new file\n:x              write file and exit"
    },
    {
      "desc": "Movement",
      "code": "k\nh   l         basic motion\nj"
    },
    {
      "desc": null,
      "code": "w               next start of word\nW               next start of whitespace-delimited word\ne               next end of word\nE               next end of whitespace-delimited word\nb               previous start of word\nB               previous start of whitespace-delimited word\n0               start of line\n$               end of line\ngg              go to first line in file\nG               go to end of file\ngk\t\tmove down one displayed line\ngj\t\tmove up one displayed line"
    },
    {
      "desc": "Enter insertion mode and:",
      "code": "a               append after the cursor\nA               append at the end of the line\ni               insert before the cursor\nI               insert at the beginning of the line\no               create a new line under the cursor\nO               create a new line above the cursor\nR               enter insert mode but replace instead of inserting chars\n:r {file}       insert from file"
    },
    {
      "desc": "Editing",
      "code": "u               undo\nyy              yank (copy) a line\ny{motion}       yank text that {motion} moves over\np               paste after cursor\nP               paste before cursor\n<Del> or x      delete a character\ndd              delete a line\nd{motion}       delete text that {motion} moves over"
    },
    {
      "desc": "Search and replace with the `:substitute` (aka `:s`) command",
      "code": ":s/foo/bar/\treplace the first match of 'foo' with 'bar' on the current line only\n:s/foo/bar/g\treplace all matches (`g` flag) of 'foo' with 'bar' on the current line only\n:%s/foo/bar/g\treplace all matches of 'foo' with 'bar' in the entire file (`:%s`)\n:%s/foo/bar/gc\task to manually confirm (`c` flag) each replacement"
    },
    {
      "desc": "Examples:",
      "code": "50k         moves 50 lines up\n2dw         deletes 2 words\n5yy         copies 5 lines\n42G         go to line 42"
    },
    {
      "desc": "Multiple windows",
      "code": ":e filename      - edit another file\n:split filename  - split window and load another file\nctrl-w up arrow  - move cursor up a window\nctrl-w ctrl-w    - move cursor to another window (cycle)\nctrl-w_          - maximize current window\nctrl-w=          - make all equal size\n10 ctrl-w+       - increase window size by 10 lines\n:vsplit file     - vertical split\n:sview file      - same as split, but readonly\n:hide            - close current window\n:only            - keep only this window open\n:ls              - show current buffers\n:.! <command>    - shell out"
    },
    {
      "desc": "move to N, next, previous, first last buffers",
      "code": ":bn              - goes to next buffer\n:bp              - goes to prev buffer\n:bf              - goes to first buffer\n:bl              - goes to last buffer\n:b 2             - open buffer #2 in this window\n:new             - open a new buffer\n:vnew            - open a new vertical buffer\n:bd 2            - deletes buffer 2\n:wall            - writes all buffers\n:ball            - open a window for all buffers\n:bunload         - removes buffer from window\n:taball          - open a tab for all buffers"
    },
    {
      "desc": "Pointers back",
      "code": "ctrl-o"
    },
    {
      "desc": "Pointers forward",
      "code": "ctrl-o"
    },
    {
      "desc": "Super search",
      "code": "ctrl-p"
    },
    {
      "desc": "To sort  a visual range on column 1 as a number:",
      "code": ":'<,'>!sort -gk 1 -t ,"
    },
    {
      "desc": "before the cursor:",
      "code": "nmap <F2> \"= system(\"uuidgen\")[:-2]<C-M>P"
    },
    {
      "desc": "The _ in the d _ command ensures registers and clipboards are not changed.",
      "code": ":g/FOO/d _"
    }
  ],
  "jq": [
    {
      "desc": "To pretty print the json:",
      "code": "jq \".\" < filename.json"
    },
    {
      "desc": "To access the value at key \"foo\":",
      "code": "jq '.foo'"
    },
    {
      "desc": "To access first list item:",
      "code": "jq '.[0]'"
    },
    {
      "desc": "to slice and dice:",
      "code": "jq '.[2:4]'\njq '.[:3]'\njq '.[-2:]'"
    },
    {
      "desc": "to extract all keys from json:",
      "code": "jq keys"
    },
    {
      "desc": "to sort by a key:",
      "code": "jq '.foo | sort_by(.bar)'"
    },
    {
      "desc": "to count elements:",
      "code": "jq '.foo | length'"
    },
    {
      "desc": "print only selected fields:",
      "code": "jq '.foo[] | {field_1,field_2}'"
    },
    {
      "desc": "print selected fields as text instead of json:",
      "code": "jq '.foo[] | {field_1,field_2} | join(\" \")'"
    },
    {
      "desc": "only print records where given field matches a value",
      "code": "jq '.foo[] | select(.field_1 == \"value_1\")'"
    }
  ],
  "kubectl": [
    {
      "desc": "To display list of all available commands:",
      "code": "kubectl -h"
    },
    {
      "desc": "To display an explanation of a specific command:",
      "code": "kubectl command_name -h"
    },
    {
      "desc": "To display complete list of supported resources:",
      "code": "kubectl api-resources"
    },
    {
      "desc": "To display an explanation of a specific resource:",
      "code": "kubectl explain resource_name"
    },
    {
      "desc": "To display an explanation of a specific field of resource:",
      "code": "kubectl explain resource_name.field_name"
    },
    {
      "desc": "To display list of global command-line options:",
      "code": "kubectl options"
    },
    {
      "desc": "To set up `kubectl` autocomplete in bash (press Tab to use):",
      "code": "source <(kubectl completion bash)"
    },
    {
      "desc": "To display all resources in all namespaces:",
      "code": "kubectl get all -A"
    },
    {
      "desc": "To order events by `creationTimestamp`:",
      "code": "kubectl get events --sort-by='.metadata.creationTimestamp'"
    },
    {
      "desc": "To switch context of a specific cluster:",
      "code": "kubectl config use-context CONTEXT_NAME [options]"
    }
  ],
  "tmux": [
    {
      "desc": "To start tmux:",
      "code": "tmux"
    },
    {
      "desc": "To detach from tmux:",
      "code": "Ctrl-b d"
    },
    {
      "desc": "To restore tmux session:",
      "code": "tmux attach"
    },
    {
      "desc": "To detach an already attached session (great if you are moving devices with different screen resolutions):",
      "code": "tmux attach -d"
    },
    {
      "desc": "To display session:",
      "code": "tmux ls"
    },
    {
      "desc": "To rename session:",
      "code": "Ctrl-b $"
    },
    {
      "desc": "To switch session:",
      "code": "Ctrl-b s"
    },
    {
      "desc": "To start a shared session:",
      "code": "tmux -S /tmp/your_shared_session\nchmod 777 /tmp/your_shared_session"
    },
    {
      "desc": "To help screen (Q to quit):",
      "code": "Ctrl-b ?"
    },
    {
      "desc": "To scroll in window:",
      "code": "Ctrl-b PageUp/PageDown"
    },
    {
      "desc": "To reload configuration file",
      "code": "Ctrl-b : source-file /path/to/file"
    },
    {
      "desc": "To create a window:",
      "code": "Ctrl-b c"
    },
    {
      "desc": "To go next window:",
      "code": "Ctrl-b n"
    },
    {
      "desc": "To destroy a window:",
      "code": "Ctrl-b x"
    },
    {
      "desc": "To switch between windows:",
      "code": "Ctrl-b [0-9]\nCtrl-b Arrows"
    },
    {
      "desc": "To split windows horizontally:",
      "code": "Ctrl-b %"
    },
    {
      "desc": "To split windows vertically:",
      "code": "Ctrl-b \""
    },
    {
      "desc": "To swap windows:",
      "code": "Ctrl-b :swap-window -s [0-9] -t [0-9]"
    }
  ],
  "screen": [
    {
      "desc": "To start a new named screen session:",
      "code": "screen -S <session-name>"
    },
    {
      "desc": "To detach from the current session:",
      "code": "Press Ctrl+A then press d"
    },
    {
      "desc": "To re-attach a detached session:",
      "code": "screen -r <session-name>"
    },
    {
      "desc": "To list all screen sessions:",
      "code": "screen -ls"
    },
    {
      "desc": "To quit a session:",
      "code": "screen -XS <session-name> quit"
    }
  ],
  "ffmpeg": [
    {
      "desc": "To print file metadata:",
      "code": "ffmpeg -i <file>"
    },
    {
      "desc": "To convert all m4a files to mp3",
      "code": "for f in *.m4a; do ffmpeg -i \"$f\" -acodec libmp3lame -vn -b:a 320k \"${f%.m4a}.mp3\"; done"
    },
    {
      "desc": "-g : GOP, for searchability",
      "code": "ffmpeg -i input.foo -vcodec bar -acodec baz -b:v 21000k -b:a 320k -g 150 -threads 4 output.bar"
    },
    {
      "desc": "To convert image sequence to video:",
      "code": "ffmpeg -r 18 -pattern_type glob -i '*.png' -b:v 21000k -s hd1080 -vcodec vp9 -an -pix_fmt yuv420p -deinterlace output.ext"
    },
    {
      "desc": "To combine video and audio into one file",
      "code": "ffmpeg -i video.ext -i audio.ext -c:v copy -c:a copy output.ext"
    },
    {
      "desc": "To add ass subtitle to the video",
      "code": "ffmpeg -i input_video.mp4 -vf ass=sub.ass output_video_subtitles.mp4"
    },
    {
      "desc": "To convert webm to mp4",
      "code": "ffmpeg -i input_video.webm output_video.mp4"
    },
    {
      "desc": "To convert mp4 to mov",
      "code": "ffmpeg -i input_video.mp4 -acodec copy -vcodec copy -f mov output_video.mov"
    },
    {
      "desc": "To convert mov to mp4",
      "code": "ffmpeg -i input_video.mov -vcodec copy -acodec copy output_video.mp4"
    },
    {
      "desc": "-autoexit : closes ffplay as soon as the audio finishes",
      "code": "ffmpeg -ss 00:34:24.85 -t 10 -i path/to/file.mp4 -f mp3 pipe:play | ffplay -i pipe:play -autoexit"
    },
    {
      "desc": "See also https://stackoverflow.com/questions/7333232/how-to-concatenate-two-mp4-files-using-ffmpeg",
      "code": "cat mylist.txt\nfile '/path/to/file1'\nfile '/path/to/file2'\nfile '/path/to/file3'"
    },
    {
      "desc": null,
      "code": "ffmpeg -f concat -safe 0 -i mylist.txt -c copy output.mp4"
    }
  ],
  "zip": [
    {
      "desc": "To create zip file:",
      "code": "zip archive.zip file1 directory/"
    },
    {
      "desc": "To create zip file from directory:",
      "code": "zip -r archive.zip directory/"
    },
    {
      "desc": "To create zip file with password:",
      "code": "zip -P password archive.zip file1"
    },
    {
      "desc": "To join a split zip file (.zip, .z01, .z02, etc):",
      "code": "zip -FF splitZipfile.zip --out joined.zip"
    },
    {
      "desc": "To list, test and extract zip archives, see unzip:",
      "code": "cheat unzip"
    }
  ],
  "unzip": [
    {
      "desc": "To extract an archive:",
      "code": "unzip <archive>"
    },
    {
      "desc": "To extract an archive to a specific directory:",
      "code": "unzip <archive> -d <directory>"
    },
    {
      "desc": "To test integrity of archive:",
      "code": "unzip -tq <archive>"
    },
    {
      "desc": "To list files and directories an archive:",
      "code": "unzip -l <archive>"
    }
  ],
  "7z": [
    {
      "desc": null,
      "code": "7z [Args] [archive.7z] [files / folders to archive]\nA file archiver with highest compression ratio"
    },
    {
      "desc": null,
      "code": "Args:\na       add\nd       delete\ne       extract\nl       list\nt       test\nu       update\nx       extract with full paths"
    },
    {
      "desc": null,
      "code": "DO NOT USE the 7-zip format for backup purpose on Linux/Unix.\n7-zip does not store the owner/group of the file."
    },
    {
      "desc": null,
      "code": "On Linux/Unix, in order to backup directories you must use tar :\n- to backup a directory  : tar cf - directory | 7z a -si directory.tar.7z\n- to restore your backup : 7z x -so directory.tar.7z | tar xf -"
    },
    {
      "desc": null,
      "code": "If  you  want  to send files and directories (not the owner of file) to others\nUnix/MacOS/Windows users, you can use the 7-zip format."
    },
    {
      "desc": null,
      "code": "Example 1: Quick and Easy - Add all files in dir1 to archive.7z with Default Settings.\n7z a archive.7z  dir1"
    },
    {
      "desc": null,
      "code": "Example 2: Add all files in dir1 to archive.7z with Max Compression\n7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on archive.7z dir1"
    },
    {
      "desc": null,
      "code": "-t7z        7z archive\n-m0=lzma    lzma method\n-mx=9       level of compression = 9 (ultra)\n-mfb=64     number of fast bytes for lzma = 64\n-md=32m     dictionary size = 32 Mb\n-ms=on      solid archive = on"
    },
    {
      "desc": null,
      "code": "Example 3: Add (store) all files in dir1 to archive.7z with No Compression\n7z a -m0=copy archive.7z dir1"
    },
    {
      "desc": null,
      "code": "7z exit codes:"
    },
    {
      "desc": null,
      "code": "0       normal (no errors or warnings)\n1       warning (non-fatal errors)\n2       fatal error\n7       bad cli arguments\n8       not enough memory for operation\n255     process was interrupted"
    }
  ],
  "chmod": [
    {
      "desc": "Add execute for all (myscript.sh)",
      "code": "chmod a+x myscript.sh"
    },
    {
      "desc": "Set user to read/write/execute, group/global to read only (myscript.sh), symbolic mode",
      "code": "chmod u=rwx, go=r myscript.sh"
    },
    {
      "desc": "Remove write from user/group/global (myscript.sh), symbolic mode",
      "code": "chmod a-w myscript.sh"
    },
    {
      "desc": "Remove read/write/execute from user/group/global (myscript.sh), symbolic mode",
      "code": "chmod = myscript.sh"
    },
    {
      "desc": "Set user to read/write and group/global read (myscript.sh), octal notation",
      "code": "chmod 644 myscript.sh"
    },
    {
      "desc": "Set user to read/write/execute and group/global read/execute (myscript.sh), octal notation",
      "code": "chmod 755 myscript.sh"
    },
    {
      "desc": "Set user/group/global to read/write (myscript.sh), octal notation",
      "code": "chmod 666 myscript.sh"
    },
    {
      "desc": "Roles",
      "code": "u - user (owner of the file)\ng - group (members of file's group)\no - global (all users who are not owner and not part of group)\na - all (all 3 roles above)"
    },
    {
      "desc": "Numeric representations",
      "code": "7 - full (rwx)\n6 - read and write (rw-)\n5 - read and execute (r-x)\n4 - read only (r--)\n3 - write and execute (-wx)\n2 - write only (-w-)\n1 - execute only (--x)\n0 - none (---)"
    },
    {
      "desc": "See: `man -M /usr/share/man chmod`",
      "code": "/bin/chmod -a# 0 /path/to/file"
    }
  ],
  "chown": [
    {
      "desc": "Change a file's owner:",
      "code": "chown <user> <file>"
    },
    {
      "desc": "Change a file's owner and group:",
      "code": "chown <user>:<group> <file>"
    },
    {
      "desc": "Set user to match group value",
      "code": "chown <user>: <file>"
    },
    {
      "desc": "Set group to match user value",
      "code": "chown :<group> <file>"
    },
    {
      "desc": "Change a directory's owner recursively:",
      "code": "chown -R <user> <directory>"
    },
    {
      "desc": "Change ownership to match another file:",
      "code": "chown --reference=<reference-file> <file>"
    }
  ],
  "ls": [
    {
      "desc": "To display everything in <dir>, excluding hidden files:",
      "code": "ls <dir>"
    },
    {
      "desc": "To display everything in <dir>, including hidden files:",
      "code": "ls -a <dir>"
    },
    {
      "desc": "To display all files, along with the size (with unit suffixes) and timestamp:",
      "code": "ls -lh <dir>"
    },
    {
      "desc": "To display files, sorted by size:",
      "code": "ls -S <dir>"
    },
    {
      "desc": "To display directories only:",
      "code": "ls -d */ <dir>"
    },
    {
      "desc": "To display directories only, include hidden:",
      "code": "ls -d .*/ */ <dir>"
    },
    {
      "desc": "To display all files sorted by changed date, most recent first:",
      "code": "ls -ltc"
    },
    {
      "desc": "To display files sorted by create time:",
      "code": "ls -lt"
    },
    {
      "desc": "To display files in a single column:",
      "code": "ls -1"
    },
    {
      "desc": "see also `cheat chmod` for `/bin/chmod` options for ACLs",
      "code": "/bin/ls -le"
    },
    {
      "desc": "To show all the subtree files (Recursive Mode):",
      "code": "ls -R"
    }
  ],
  "cp": [
    {
      "desc": "To copy a file:",
      "code": "cp ~/Desktop/foo.txt ~/Downloads/foo.txt"
    },
    {
      "desc": "To copy a directory:",
      "code": "cp -r ~/Desktop/cruise_pics/ ~/Pictures/"
    },
    {
      "desc": "To create a copy but ask to overwrite if the destination file already exists:",
      "code": "cp -i ~/Desktop/foo.txt ~/Documents/foo.txt"
    },
    {
      "desc": "To create a backup file with date:",
      "code": "cp foo.txt{,.\"$(date +%Y%m%d-%H%M%S)\"}"
    },
    {
      "desc": "Note this does NOT work (note trailing '/'):  cp -P /path/to/symlink-dir/",
      "code": "cp -P <symlink-dir> <dest-dir>"
    },
    {
      "desc": "To copy sparsely:",
      "code": "cp --sparse=always <src> <dest>"
    }
  ],
  "mv": [
    {
      "desc": "To move a file from one place to another:",
      "code": "mv <src> <dest>"
    },
    {
      "desc": "(This will override any previous -i or -n args)",
      "code": "mv -f <src> <dest>"
    },
    {
      "desc": "(This will override any previous -f or -n args)",
      "code": "mv -i <src> <dest>"
    },
    {
      "desc": "(This will override any previous -f or -i args)",
      "code": "mv -n <src> <dest>"
    },
    {
      "desc": "To move listed file(s) to a directory",
      "code": "mv -t <dest> <file>..."
    }
  ],
  "rm": [
    {
      "desc": "To remove all files and subdirs in <dir>:",
      "code": "rm -rf <dir>"
    },
    {
      "desc": "To ignore non-existent files:",
      "code": "rm -f <dir>"
    },
    {
      "desc": "To remove a file with this inode:",
      "code": "find /tmp/ -inum 6666 -exec rm -i '{}' \\;"
    }
  ],
  "mysql": [
    {
      "desc": "To connect to a database:",
      "code": "mysql -h <host> -u <username> -p"
    },
    {
      "desc": "To backup all databases:",
      "code": "mysqldump --all-databases --all-routines -u <username> -p > ~/dump.sql"
    },
    {
      "desc": "To restore all databases:",
      "code": "mysql -u <username> -p  < ~/fulldump.sql"
    },
    {
      "desc": "To create a database in utf8 charset:",
      "code": "CREATE DATABASE owa CHARACTER SET utf8 COLLATE utf8_general_ci;"
    },
    {
      "desc": "To add a user and give rights on the given database:",
      "code": "GRANT ALL PRIVILEGES ON database.* TO 'user'@'localhost'IDENTIFIED BY 'password' WITH GRANT OPTION;"
    },
    {
      "desc": "To list the privileges granted to the account that you are using to connect to the server. Any of the 3 statements will work. :",
      "code": "SHOW GRANTS FOR CURRENT_USER();\nSHOW GRANTS;\nSHOW GRANTS FOR CURRENT_USER;"
    },
    {
      "desc": "Basic SELECT Statement:",
      "code": "SELECT * FROM tbl_name;"
    },
    {
      "desc": "Basic INSERT Statement:",
      "code": "INSERT INTO tbl_name (col1,col2) VALUES(15,col1*2);"
    },
    {
      "desc": "Basic UPDATE Statement:",
      "code": "UPDATE tbl_name SET col1 = \"example\";"
    },
    {
      "desc": "Basic DELETE Statement:",
      "code": "DELETE FROM tbl_name WHERE user = 'jcole';"
    },
    {
      "desc": "To check stored procedure:",
      "code": "SHOW PROCEDURE STATUS;"
    },
    {
      "desc": "To check stored function:",
      "code": "SHOW FUNCTION STATUS;"
    }
  ],
  "psql": [
    {
      "desc": "Connect to a specific database:",
      "code": "psql -U <username> -h <host> -d <database>"
    },
    {
      "desc": "Get databases on a server:",
      "code": "psql -U <username> -h <host> --list"
    },
    {
      "desc": "Execute sql query and save output to file:",
      "code": "psql -U <username> -d <database> -c 'select * from tableName;' -o <outfile>"
    },
    {
      "desc": "Execute query and get tabular html output:",
      "code": "psql -U <username> -d <database> -H -c 'select * from tableName;'"
    },
    {
      "desc": "(if column names in the first row are not needed, remove the word 'header')",
      "code": "psql -U <username> -d <database> -c 'copy (select * from tableName) to stdout with csv header;' -o <outfile>"
    },
    {
      "desc": "Read commands from file:",
      "code": "psql -f <outfile>"
    },
    {
      "desc": "Restore databases from file:",
      "code": "psql -f <outfile> <username>"
    }
  ],
  "sqlite3": [
    {
      "desc": "To create database and launch interactive shell:",
      "code": "sqlite3 <database>"
    },
    {
      "desc": "To create table:",
      "code": "sqlite3 <database> \"create table os(id integer primary key, name text, year integer);\""
    },
    {
      "desc": "To insert data:",
      "code": "sqlite3 <database> \"insert into 'os' values(1,'linux',1991);\""
    },
    {
      "desc": "To list tables:",
      "code": "sqlite3 <database> \".tables\""
    },
    {
      "desc": "To describe table:",
      "code": "sqlite3 <database> \".schema 'os'\""
    },
    {
      "desc": "To view records in table:",
      "code": "sqlite3 <database> \"select * from 'os';\""
    },
    {
      "desc": "To view records in table conditionally:",
      "code": "sqlite3 <database> \"select * from 'os' where year='1991';\""
    },
    {
      "desc": "To view records with fuzzy matching:",
      "code": "sqlite3 <database> \"select * from 'os' where year like '19%';\""
    },
    {
      "desc": "To create a table named `cities` and import a csv into it:",
      "code": "sqlite3 <database> \".import /path/to/city.csv cities\""
    }
  ]
};
